version: '3.8'
services:
  stats-server:
    build: ./stats/stats-server
    image: ewm-stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=ewm-stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /ewm-stats-db
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./service
    image: emw-service-image
    container_name: emw-service
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ewm-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /ewm-service-db
