version: '3.8'
services:
  stats-server:
    build: ./statistic/statistic-server
    image: statistic-server
    container_name: statistic-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=stats-db
        DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: statsDb
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - application.name=main
      - stats-server.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/emwDb
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=emwDb
      - DB_HOST=db
        DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: emwDb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=emwDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres